version: '3.4'

services:
  distributedtesting:
    image: ${DOCKER_REGISTRY-}distributedtesting
    build:
      context: .
      dockerfile: DistributedTesting/Dockerfile

  distributedtesting.services.test1:
    image: ${DOCKER_REGISTRY-}distributedtestingservicestest1
    build:
      context: .
      dockerfile: DistributedTesting.Services.Test1/Dockerfile


  distributedtesting.services.test2:
    image: ${DOCKER_REGISTRY-}distributedtestingservicestest2
    build:
      context: .
      dockerfile: DistributedTesting.Services.Test2/Dockerfile

