version: "3.5"

services:
  mongo:
    image: mongo:4
    container_name: mongo
    ports:
      - 27017:27017
    networks:
      - distributedtesting
    # network_mode: host
    volumes:
      - mongo:/data/db

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - distributedtesting
    # network_mode: host
    volumes: 
      - rabbitmq:/var/lib/rabbitmq

  redis:
    image: redis
    container_name: redis
    ports:
      - 6379:6379
    networks:
      - distributedtesting
    # network_mode: host
    volumes: 
      - redis:/data

  consul:
    image: consul
    container_name: consul
    ports:
      - 8500:8500
    networks:
      - distributedtesting
    # network_mode: host
    volumes:
      - consul:/consul/data

  fabio:
    image: fabiolb/fabio
    container_name: fabio
    environment:
    - FABIO_REGISTRY_CONSUL_ADDR=consul:8500
    networks:
      - distributedtesting
    # network_mode: host
    ports:
    - 9998:9998
    - 9999:9999

  vault:
    image: vault
    container_name: vault
    ports:
      - 8200:8200
    networks:
      - distributedtesting
    # network_mode: host
    environment:
      - VAULT_ADDR=http://127.0.0.1:8200
      - VAULT_DEV_ROOT_TOKEN_ID=secret
    cap_add:
      - IPC_LOCK
  jaeger:
    image: jaegertracing/all-in-one
    container_name: jaeger
    ports:
      - 5775:5775/udp
      - 5778:5778
      - 6831:6831/udp
      - 6832:6832/udp
      - 9411:9411
      - 14268:14268
      - 16686:16686
    networks:
      - distributedtesting

  seq:
    image: datalust/seq 
    container_name: seq
    environment:
      - ACCEPT_EULA=Y
    ports:
      - 5341:80
    networks:
      - distributedtesting
    # network_mode: host
    volumes: 
      - seq:/data

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.0.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - distributedtesting
  
  kibana:
    image: docker.elastic.co/kibana/kibana:7.0.0
    container_name: kibana
    ports:
      - 5601:5601
    networks:
      - distributedtesting

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    networks:
      - distributedtesting
    # network_mode: host
    volumes:
      - grafana:/var/lib/grafana

  influxdb:
    image: influxdb
    container_name: influxdb
    ports:
      - '8086:8086'
    networks:
      - distributedtesting
    # network_mode: host
    volumes:
      - influxdb:/var/lib/influxdb

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - '9090:9090'
    networks:
      - distributedtesting
    # network_mode: host
    volumes:
      - prometheus:/prometheus
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
        
networks:
  distributedtesting:
    name: distributedtesting-network

volumes:
  mongo:
    driver: local
  rabbitmq:
    driver: local
  redis:
    driver: local
  consul:
    driver: local
  seq:
    driver: local
  elasticsearch:
    driver: local
  grafana:
    driver: local
  influxdb:
    driver: local
  prometheus:
    driver: local