version: "3.5"

services:
  jaeger:
    image: jaegertracing/all-in-one
    container_name: jaeger
    ports:
      - 5775:5775/udp
      - 5778:5778
      - 6831:6831/udp
      - 6832:6832/udp
      - 9411:9411
      - 14268:14268
      - 16686:16686
    networks:
      - distributedtesting

  seq:
    image: datalust/seq 
    container_name: seq
    environment:
      - ACCEPT_EULA=Y
    ports:
      - 5341:80
    networks:
      - distributedtesting
    # network_mode: host
    volumes: 
      - seq:/data

networks:
  distributedtesting:
    name: distributedtesting-network

volumes:
  seq:
    driver: local