FROM mcr.microsoft.com/dotnet/core/sdk:2.2
ARG BUILD_CONFIGURATION=Debug
ENV ASPNETCORE_ENVIRONMENT=Development
ENV DOTNET_USE_POLLING_FILE_WATCHER=true
EXPOSE 80

WORKDIR /src
COPY ["DistributedTesting.Common/DistributedTesting.Common.csproj", "DistributedTesting.Common/"]
COPY ["DistributedTesting.Services.Test1/DistributedTesting.Services.Test1.csproj", "DistributedTesting.Services.Test1/"]

RUN dotnet restore "DistributedTesting.Services.Test1/DistributedTesting.Services.Test1.csproj"
COPY . .
WORKDIR "/src/DistributedTesting.Services.Test1"
RUN dotnet build --no-restore "DistributedTesting.Services.Test1.csproj" -c $BUILD_CONFIGURATION

RUN echo "exec dotnet run --no-build --no-launch-profile -c $BUILD_CONFIGURATION --" > /entrypoint.sh

ENTRYPOINT ["/bin/bash", "/entrypoint.sh"]